name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Debugging secrets
      run: echo username ${{DOCKERHUB_USERNAME}} password ${{ DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Login to Docker hub
      run: docker login --username ${{ DOCKERHUB_USERNAME }} --password ${{ DOCKERHUB_ACCESS_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ DOCKERHUB_USERNAME }}/ahmed-image
      
    - name: Push the Docker image to Docker hub
      run: docker push ${{ DOCKERHUB_USERNAME }}/ahmed-image
